<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CgmConfigAdmin\Module'                                  => __DIR__ . '/Module.php',
    'CgmConfigAdmin\Controller\ConfigOptionsController'      => __DIR__ . '/src/CgmConfigAdmin/Controller/ConfigOptionsController.php',
    'CgmConfigAdmin\Form\ConfigOptions'                      => __DIR__ . '/src/CgmConfigAdmin/Form/ConfigOptions.php',
    'CgmConfigAdmin\Options\ConfigOption'                    => __DIR__ . '/src/CgmConfigAdmin/Options/ConfigOption.php',
    'CgmConfigAdmin\Options\ModuleOptions'                   => __DIR__ . '/src/CgmConfigAdmin/Options/ModuleOptions.php',
    'CgmConfigAdmin\Service\ConfigAdmin'                     => __DIR__ . '/src/CgmConfigAdmin/Service/ConfigAdmin.php',
    'CgmConfigAdmin\View\Helper\CgmConfigAdminAccordionForm' => __DIR__ . '/src/CgmConfigAdmin/View/Helper/CgmConfigAdminAccordionForm.php',
    'CgmConfigAdmin\View\Helper\CgmConfigAdminFieldsetForm'  => __DIR__ . '/src/CgmConfigAdmin/View/Helper/CgmConfigAdminFieldsetForm.php',
    'CgmConfigAdminTest\Framework\TestCase'                  => __DIR__ . '/tests/CgmConfigAdminTest/Framework/TestCase.php',
    'CgmConfigAdminTest\SampleTest'                          => __DIR__ . '/tests/CgmConfigAdminTest/SampleTest.php',
);